# Generated by Django 4.2.4 on 2024-02-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowhistory',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
